// 📱 Azeem's Premium Mobiles Collection 2026
export const mobiles = [
  {
    id: 200,
    name: "iPhone 15 Pro Max",
    image: "https://tse4.mm.bing.net/th/id/OIP.L82uoqcjR5wBrezejq2SlQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "Titanium build with A17 Pro chip. The ultimate iPhone experience.",
    category: "Mobiles",
    brand: "Apple",
    rating: 4.9,
    stock: 5,
    warranty: "1 Year International",
    delivery: "Free Delivery",
    price: 445000,
    specs: {
      display: "6.7\" LTPO Super Retina XDR OLED, 120Hz",
      processor: "Apple A17 Pro (3 nm)",
      mainCamera: "48MP (Wide) + 12MP (Periscope Tele) + 12MP (Ultrawide)",
      selfieCamera: "12MP, f/1.9, PDAF, OIS",
      battery: "4441 mAh, 15W MagSafe, 50% in 30min",
      build: "Titanium frame, Sapphire crystal glass",
      features: "Action Button, USB-C 3.0, FaceID, IP68"
    }
  },
  {
    id: 202,
    name: "Samsung Galaxy S24 Ultra",
    image: "https://tse1.mm.bing.net/th/id/OIP.FpxLz2z3K0uTLDDu0ZNBMgHaHc?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "Galaxy AI powered with 200MP camera and built-in S Pen.",
    category: "Mobiles",
    brand: "Samsung",
    rating: 4.8,
    stock: 12,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 385000,
    specs: {
      display: "6.8\" Dynamic LTPO AMOLED 2X, 2600 nits",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "200MP + 50MP (5x) + 10MP (3x) + 12MP (Ultrawide)",
      selfieCamera: "12MP, f/2.2, Dual Pixel PDAF",
      battery: "5000 mAh, 45W Wired, 15W Wireless",
      build: "Titanium Frame, Gorilla Armor Glass",
      features: "S-Pen, Galaxy AI, 8K Video, IP68"
    }
  },
  {
    id: 203,
    name: "Google Pixel 8 Pro",
    image: "https://static1.howtogeekimages.com/wordpress/wp-content/uploads/2023/11/pixel-8pro.png",
    description: "Best AI camera phone with Magic Editor and 7 years of updates.",
    category: "Mobiles",
    brand: "Google",
    rating: 4.7,
    stock: 8,
    warranty: "1 Year Local",
    delivery: "Free Delivery",
    price: 265000,
    specs: {
      display: "6.7\" LTPO OLED, 120Hz, 2400 nits",
      processor: "Google Tensor G3 (4 nm)",
      mainCamera: "50MP (Wide) + 48MP (5x Tele) + 48MP (Ultrawide)",
      selfieCamera: "10.5MP, f/2.2, Ultrawide",
      battery: "5050 mAh, 30W Wired, 23W Wireless",
      build: "Aluminum Frame, Gorilla Glass Victus 2",
      features: "AI Magic Eraser, Best Take, IP68"
    }
  },
  {
    id: 204,
    name: "OnePlus 12 5G",
    image: "https://www.gadgetpilipinas.net/wp-content/uploads/2024/04/OnePlus-12-All-Colors.jpg",
    description: "Fast and Smooth. 4th Gen Hasselblad Camera for Mobile.",
    category: "Mobiles",
    brand: "OnePlus",
    rating: 4.6,
    stock: 15,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 210000,
    specs: {
      display: "6.82\" LTPO AMOLED, 1B colors, 120Hz",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (Wide) + 64MP (3x Periscope) + 48MP (Ultrawide)",
      selfieCamera: "32MP, f/2.4, Wide",
      battery: "5400 mAh, 80W Wired, 50W Wireless",
      build: "Glass back, Aluminum frame",
      features: "Hasselblad Calibration, Alert Slider"
    }
  },
  {
    id: 205,
    name: "Nothing Phone (2)",
    image: "https://www.mobiledokan.co/wp-content/uploads/2023/01/Nothing-Phone-2-Grey-500x500.jpg",
    description: "Unique Glyph Interface with a focus on mindful tech usage.",
    category: "Mobiles",
    brand: "Nothing",
    rating: 4.5,
    stock: 10,
    warranty: "1 Year Local",
    delivery: "Free Delivery",
    price: 145000,
    specs: {
      display: "6.7\" LTPO OLED, 120Hz, HDR10+",
      processor: "Snapdragon 8+ Gen 1 (4 nm)",
      mainCamera: "50MP (Wide) + 50MP (Ultrawide)",
      selfieCamera: "32MP, f/2.5",
      battery: "4700 mAh, 45W Wired, 15W Wireless",
      build: "Transparent glass back, Aluminum frame",
      features: "Glyph Lighting, Nothing OS 2.5"
    }
  },
  {
    id: 206,
    name: "Xiaomi 14 Ultra",
    image: "https://tse3.mm.bing.net/th/id/OIP.u0SVzYi_iH1bEGPUMO5IzQHaEI?rs=1&pid=ImgDetMain&o=7&rm=3.png",
    description: "Leica Summilux optical lens for professional mobile photography.",
    category: "Mobiles",
    brand: "Xiaomi",
    rating: 4.8,
    stock: 4,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 275000,
    specs: {
      display: "6.73\" LTPO AMOLED, 68B colors, 120Hz",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (1-inch) + 50MP (Tele) + 50MP (Periscope) + 50MP",
      selfieCamera: "32MP, HDR10+",
      battery: "5000 mAh, 90W Wired, 80W Wireless",
      build: "Eco-leather or Glass, Titanium frame",
      features: "Leica Optics, Log Recording, 8K Video"
    }
  },
  {
    id: 207,
    name: "ASUS ROG Phone 8 Pro",
    image: "https://tse4.mm.bing.net/th/id/OIP.GZf1X6ujrjYBDCGBfI9C4gHaEK?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "The world's most powerful gaming phone with 165Hz display.",
    category: "Mobiles",
    brand: "ASUS",
    rating: 4.9,
    stock: 3,
    warranty: "1 Year Local",
    delivery: "Free Delivery",
    price: 295000,
    specs: {
      display: "6.78\" LTPO AMOLED, 165Hz, 2500 nits",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (Gimbal OIS) + 32MP (Tele) + 13MP (Ultrawide)",
      selfieCamera: "32MP, f/2.5",
      battery: "5500 mAh, 65W Wired, 15W Wireless",
      build: "Glass front/back, Aluminum frame",
      features: "AniMe Vision Mini-LED, AirTrigger buttons"
    }
  },
  {
    id: 208,
    name: "Sony Xperia 1 V",
    image: "https://i.gadgets360cdn.com/large/Sony_Xperia_1_V_main_1683787505428.jpg",
    description: "Unprecedented 4K HDR OLED display for cinema lovers.",
    category: "Mobiles",
    brand: "Sony",
    rating: 4.4,
    stock: 6,
    warranty: "1 Year International",
    delivery: "Free Delivery",
    price: 240000,
    specs: {
      display: "6.5\" 4K HDR OLED, 21:9 ratio, 120Hz",
      processor: "Snapdragon 8 Gen 2 (4 nm)",
      mainCamera: "48MP (Wide) + 12MP (Tele) + 12MP (Ultrawide)",
      selfieCamera: "12MP, 4K Video",
      battery: "5000 mAh, 30W Wired, Wireless charging",
      build: "Gorilla Glass Victus 2, Aluminum frame",
      features: "3.5mm Jack, MicroSD Slot, Pro Camera UI"
    }
  },
  {
    id: 209,
    name: "Motorola Edge 50 Pro",
    image: "https://i.gadgets360cdn.com/large/moto_edge_50_pro_android_headlines_inline_1709988164241.jpg",
    description: "Pantone Validated display and camera. Sleekest design.",
    category: "Mobiles",
    brand: "Motorola",
    rating: 4.3,
    stock: 14,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 135000,
    specs: {
      display: "6.7\" P-OLED, 144Hz, 2000 nits",
      processor: "Snapdragon 7 Gen 3 (4 nm)",
      mainCamera: "50MP (Wide) + 10MP (Tele) + 13MP (Ultrawide)",
      selfieCamera: "50MP, f/1.9, AF",
      battery: "4500 mAh, 125W Wired, 50W Wireless",
      build: "Acetate or Silicone leather back",
      features: "Pantone Colors, IP68, Hello UI"
    }
  },
  {
    id: 210,
    name: "Vivo X100 Pro",
    image: "https://tse3.mm.bing.net/th/id/OIP._sYNlXVt2_iuW3aiHa7u1AHaDz?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "ZEISS APO Floating Telephoto Camera. Pro-grade shots.",
    category: "Mobiles",
    brand: "Vivo",
    rating: 4.7,
    stock: 9,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 225000,
    specs: {
      display: "6.78\" LTPO AMOLED, 120Hz, 3000 nits",
      processor: "Dimensity 9300 (4 nm)",
      mainCamera: "50MP (1-inch) + 50MP (APO Tele) + 50MP (Ultrawide)",
      selfieCamera: "32MP, f/2.0",
      battery: "5400 mAh, 100W Wired, 50W Wireless",
      build: "Glass front, Eco-leather back",
      features: "ZEISS T* Coating, V3 Imaging Chip"
    }
  },
  {
    id: 211,
    name: "Oppo Find X7 Ultra",
    image: "https://tse1.mm.bing.net/th/id/OIP.T091ELxjkeDuX0pNzFayaQAAAA?w=396&h=496&rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "World's first dual periscope camera system.",
    category: "Mobiles",
    brand: "Oppo",
    rating: 4.8,
    stock: 7,
    warranty: "1 Year International",
    delivery: "Free Delivery",
    price: 260000,
    specs: {
      display: "6.82\" LTPO AMOLED, 120Hz, 4500 nits",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (1-inch) + 50MP (3x Tele) + 50MP (6x Tele) + 50MP",
      selfieCamera: "32MP, f/2.4",
      battery: "5000 mAh, 100W Wired, 50W Wireless",
      build: "Gorilla Glass Victus 2, Leather back",
      features: "Hasselblad Master Mode, IP68"
    }
  },
  {
    id: 212,
    name: "Realme GT 5 Pro",
    image: "https://i.gadgets360cdn.com/large/realme_gt_5_realme_1694075296253.jpg",
    description: "Snapdragon 8 Gen 3 with leather back finish.",
    category: "Mobiles",
    brand: "Realme",
    rating: 4.5,
    stock: 11,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 155000,
    specs: {
      display: "6.78\" AMOLED, 144Hz, 4500 nits",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (Wide) + 50MP (Periscope Tele) + 8MP (Ultrawide)",
      selfieCamera: "32MP, f/2.5",
      battery: "5400 mAh, 100W Wired, 50W Wireless",
      build: "Glass front, Vegan leather back",
      features: "Palm Unlock, 3VC Cooling System"
    }
  },
  {
    id: 213,
    name: "Huawei Mate 60 Pro",
    image: "https://cdn.kalvo.com/uploads/img/gallery/54873-huawei-mate-60-pro-5.jpg",
    description: "Satellite calling and Xmage camera technology.",
    category: "Mobiles",
    brand: "Huawei",
    rating: 4.6,
    stock: 5,
    warranty: "1 Year International",
    delivery: "Free Delivery",
    price: 280000,
    specs: {
      display: "6.82\" LTPO OLED, 120Hz, 1.07B colors",
      processor: "Kirin 9000S (7 nm)",
      mainCamera: "50MP (Wide) + 48MP (Tele) + 12MP (Ultrawide)",
      selfieCamera: "13MP + TOF 3D (Depth)",
      battery: "5000 mAh, 88W Wired, 50W Wireless",
      build: "Glass front, Aluminum frame",
      features: "Satellite Calling, Kunlun Glass 2"
    }
  },
  {
    id: 214,
    name: "Infinix Note 40 Pro",
    image: "https://tse2.mm.bing.net/th/id/OIP.pbbZdiBHdTMGT4QMq6bfjQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "FastCharge 2.0. Premium design at an affordable price.",
    category: "Mobiles",
    brand: "Infinix",
    rating: 4.2,
    stock: 25,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 78000,
    specs: {
      display: "6.78\" AMOLED, 120Hz, Curved",
      processor: "Helio G99 Ultimate",
      mainCamera: "108MP (Wide) + 2MP + 2MP",
      selfieCamera: "32MP, f/2.2",
      battery: "5000 mAh, 70W Wired, 20W Wireless",
      build: "Glass front, Silicone back",
      features: "Magnetic Charging, JBL Audio"
    }
  },
  {
    id:216,
    name: "ZTE Nubia Z60 Ultra",
    image: "https://fdn2.gsmarena.com/vv/pics/zte/zte-nubia-z60-ultra-1.jpg",
    description: "Full-screen under-display camera with 35mm optical lens.",
    category: "Mobiles",
    brand: "ZTE",
    rating: 4.6,
    stock: 4,
    warranty: "1 Year Local",
    delivery: "Free Delivery",
    price: 195000,
    specs: {
      display: "6.8\" AMOLED, 120Hz, No Notch",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (35mm) + 64MP (85mm Tele) + 50MP (18mm Wide)",
      selfieCamera: "12MP (Under-display)",
      battery: "6000 mAh, 80W Wired",
      build: "IP68, Aluminum frame",
      features: "True Full Screen, Pro-Video Modes"
    }
  },{
    id: 218,
    name: "Honor Magic6 Pro",
    image: "https://tse2.mm.bing.net/th/id/OIP.mvmmK0JkJNcGIGADaVguYQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "Falcon Camera System with ultra-tough Jurhglass technology.",
    category: "Mobiles",
    brand: "Honor",
    rating: 4.8,
    stock: 6,
    warranty: "1 Year Official",
    delivery: "Free Delivery",
    price: 285000,
    specs: {
      display: "6.8\" LTPO OLED, 120Hz, 5000 nits (Peak)",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (Wide) + 180MP (Periscope Tele) + 50MP (Ultrawide)",
      selfieCamera: "50MP + TOF 3D (Depth/Biometrics)",
      battery: "5600 mAh, 80W Wired, 66W Wireless",
      build: "Glass front, Silicone polymer back, Metal frame",
      features: "Eye-tracking AI, IP68, Silicon-carbon battery"
    }
  },
  {
    id: 219,
    name: "Google Pixel Fold 2",
    image: "https://tse2.mm.bing.net/th/id/OIP.IGWf1ONBt3Y8ZD68CZLEVgHaFj?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "The thinnest foldable with Google's most powerful AI chip.",
    category: "Mobiles",
    brand: "Google",
    rating: 4.7,
    stock: 3,
    warranty: "1 Year Local",
    delivery: "Free Delivery",
    price: 495000,
    specs: {
      display: "8.0\" Foldable LTPO OLED (Inner), 6.3\" (Outer)",
      processor: "Google Tensor G4 (4 nm)",
      mainCamera: "48MP (Wide) + 10.8MP (Tele) + 10.8MP (Ultrawide)",
      selfieCamera: "10MP (Outer) + 10MP (Inner)",
      battery: "4821 mAh, 30W Wired, Wireless Charging",
      build: "Stainless Steel Hinge, Gorilla Glass Victus 2",
      features: "Gemini AI Built-in, Split Screen Pro, IPX8"
    }
  },
  {
    id: 220,
    name: "Red Magic 9 Pro+",
    image: "https://www.gizmochina.com/wp-content/uploads/2023/11/Red-Magic-9-Pro-Design-Featured.jpg",
    description: "Ultimate Gaming beast with built-in cooling fan and RGB.",
    category: "Mobiles",
    brand: "Nubia",
    rating: 4.9,
    stock: 5,
    warranty: "1 Year Local",
    delivery: "Free Delivery",
    price: 235000,
    specs: {
      display: "6.8\" AMOLED, 120Hz, 1600 nits",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (Wide) + 50MP (Ultrawide) + 2MP (Macro)",
      selfieCamera: "16MP (Under-display Gen 5)",
      battery: "5500 mAh, 165W Wired (100% in 16 min)",
      build: "Aviation Aluminum, Glass back",
      features: "22,000 RPM Fan, Shoulder Triggers, RGB Lights"
    }
  },
  {
    id: 221,
    name: "Xiaomi Mix Fold 3",
    image: "https://tse3.mm.bing.net/th/id/OIP.hRjnPy1L33mEDzK9Gs_AmQHaHM?rs=1&pid=ImgDetMain&o=7&rm=3.jpeg",
    description: "Slimmest folding design with Leica quad camera setup.",
    category: "Mobiles",
    brand: "Xiaomi",
    rating: 4.8,
    stock: 4,
    warranty: "1 Year International",
    delivery: "Free Delivery",
    price: 410000,
    specs: {
      display: "8.03\" LTPO OLED+, 120Hz, HDR10+",
      processor: "Snapdragon 8 Gen 2 Leading Version",
      mainCamera: "50MP + 10MP (Tele) + 10MP (Periscope) + 12MP",
      selfieCamera: "20MP (Cover) + 20MP (Inner)",
      battery: "4800 mAh, 67W Wired, 50W Wireless",
      build: "Carbon Fiber back, Aluminum Frame",
      features: "Leica Optics, 4.9mm Unfolded thickness"
    }
  },
  {
    id:222,
    name: "ROG Phone 8 Edition",
    image: "https://dlcdnwebimgs.asus.com/gain/DB9A8F21-E5FF-469B-B7FD-98B669E02F48/w1000/h732",
    description: "High-performance gaming phone with IP68 and slim bezels.",
    category: "Mobiles",
    brand: "ASUS",
    rating: 4.9,
    stock: 7,
    warranty: "1 Year Local",
    delivery: "Free Delivery",
    price: 265000,
    specs: {
      display: "6.78\" LTPO Samsung AMOLED, 165Hz",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (Gimbal OIS) + 13MP + 32MP (Tele)",
      selfieCamera: "32MP, f/2.5",
      battery: "5500 mAh, 65W Wired, 15W Wireless",
      build: "Gorilla Glass Victus 2, IP68 rated",
      features: "GameCool 8, AirTrigger Triggers, Hi-Res Audio"
    }
  },
  {
    id: 223,
    name: "Meizu 21 Pro",
    image: "https://tse4.mm.bing.net/th/id/OIP.VFZTC3s6xUK-OImvb90x3gHaE7?rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Minimalist flagship with Titan Glass and mTouch Ultra.",
    category: "Mobiles",
    brand: "Meizu",
    rating: 4.6,
    stock: 10,
    warranty: "1 Year International",
    delivery: "Free Delivery",
    price: 185000,
    specs: {
      display: "6.79\" LTPO AMOLED, 120Hz, 2K Resolution",
      processor: "Snapdragon 8 Gen 3 (4 nm)",
      mainCamera: "50MP (Wide) + 10MP (Tele) + 13MP (Ultrawide)",
      selfieCamera: "32MP, f/2.4",
      battery: "5050 mAh, 80W Wired, 50W Wireless",
      build: "Meizu Titan Glass 2.0, Metal Frame",
      features: "Flyme AI, Ultronic Fingerprint, RGB Ring Light"
    }
  }
];