// src/utils/products.js

 // src/utils/products.js

 
import { mobiles } from './mobiles';
import { laptops } from './laptops';

const electronics = [
  {
    id: 1,
    name: "Wireless Headphones",
    image: "/images/headphone.jpeg",
    description: "Noise-cancelling over-ear headphones",
    category: "Accessories",
    brand: "SoundPro",
    rating: 4.5,
    stock: 12,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 4999
  },
  {
    id: 2,
    name: "Smart Watch",
    image: "/images/smartwatch.jpeg",
    description: "Fitness tracker with heart rate monitor",
    category: "Accessories",
    brand: "FitPulse",
    rating: 4.2,
    stock: 8,
    warranty: "6 Months",
    delivery: "Free Delivery",
    price: 6999
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    image: "/images/bluethooth.jpeg",
    description: "Portable speaker with deep bass",
    category: "Electronics",
    brand: "BassBoom",
    rating: 4.7,
    stock: 20,
    warranty: "2 Years",
    delivery: "Standard Delivery",
    price: 2999
  },
  {
    id: 4,
    name: "Gaming Mouse",
    image: "/images/mouse.jpeg",
    description: "RGB mouse with 6 programmable buttons",
    category: "Accessories",
    brand: "ClickPro",
    rating: 4.3,
    stock: 15,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 2499
  },
  {
    id: 5,
    name: "Mechanical Keyboard",
    image: "/images/mechanical.jpeg",
    description: "Backlit keys with tactile feedback",
    category: "Accessories",
    brand: "KeyMaster",
    rating: 4.6,
    stock: 10,
    warranty: "2 Years",
    delivery: "Standard Delivery",
    price: 5499
  },
  {
    id: 6,
    name: "USB-C Hub",
    image: "/images/usb.jpeg",
    description: "Multiport adapter with HDMI and SD card reader",
    category: "Electronics",
    brand: "Portify",
    rating: 4.4,
    stock: 25,
    warranty: "6 Months",
    delivery: "Free Delivery",
    price: 1999
  },
  {
    id: 7,
    name: "Portable SSD",
    image: "/images/ssd.jpeg",
    description: "1TB high-speed external SSD",
    category: "Electronics",
    brand: "SpeedDrive",
    rating: 4.8,
    stock: 30,
    warranty: "3 Years",
    delivery: "Free Delivery",
    price: 8999
  },
  {
    id: 8,
    name: "Noise-Isolating Earbuds",
    image: "/images/buds.jpeg",
    description: "Compact earbuds with deep bass",
    category: "Accessories",
    brand: "TuneFlex",
    rating: 4.1,
    stock: 18,
    warranty: "1 Year",
    delivery: "Standard Delivery",
    price: 1799
  },
  {
    id: 9,
    name: "Smartphone Stand",
    image: "/images/stand.jpeg",
    description: "Adjustable aluminum mobile holder",
    category: "Accessories",
    brand: "HoldMate",
    rating: 4.0,
    stock: 40,
    warranty: "6 Months",
    delivery: "Free Delivery",
    price: 999
  },
  {
    id: 10,
    name: "Webcam HD",
    image: "/images/hd.jpeg",
    description: "1080p webcam with built-in microphone",
    category: "Electronics",
    brand: "VisionCam",
    rating: 4.3,
    stock: 22,
    warranty: "1 Year",
    delivery: "Standard Delivery",
    price: 3499
  },
  {
    id: 11,
    name: "Laptop Cooling Pad",
    image: "/images/pad.jpeg",
    description: "Silent fan base with adjustable angle",
    category: "Accessories",
    brand: "CoolMate",
    rating: 4.2,
    stock: 16,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 2299
  },
  {
    id: 12,
    name: "Wireless Charger",
    image: "/images/charger.jpeg",
    description: "Fast charging pad for smartphones",
    category: "Electronics",
    brand: "ChargeX",
    rating: 4.5,
    stock: 20,
    warranty: "6 Months",
    delivery: "Standard Delivery",
    price: 2599
  },
  {
    id: 13,
    name: "Action Camera",
    image: "/images/camera.jpeg",
    description: "Waterproof 4K camera with wide lens",
    category: "Electronics",
    brand: "GoShot",
    rating: 4.6,
    stock: 12,
    warranty: "2 Years",
    delivery: "Free Delivery",
    price: 11999
  },
  {
    id: 14,
    name: "Ergonomic Chair",
    image: "/images/chair.jpeg",
    description: "Mesh back office chair with lumbar support",
    category: "Accessories",
    brand: "SitWell",
    rating: 4.4,
    stock: 8,
    warranty: "3 Years",
    delivery: "Standard Delivery",
    price: 14999
  },
  {
    id: 15,
    name: "Mini Projector",
    image: "/images/projector.jpeg",
    description: "Portable projector with HDMI and USB",
    category: "Electronics",
    brand: "BeamBox",
    rating: 4.3,
    stock: 10,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 8999
  },
  {
    id: 16,
    name: "Smart LED Strip",
    image: "/images/strip.jpeg",
    description: "RGB light strip with app control",
    category: "Accessories",
    brand: "GlowFlex",
    rating: 4.2,
    stock: 25,
    warranty: "6 Months",
    delivery: "Standard Delivery",
    price: 1499
  },
  {
    id: 17,
    name: "Noise Meter",
    image: "/images/meter.jpeg",
    description: "Digital decibel meter for sound monitoring",
    category: "Electronics",
    brand: "SoundCheck",
    rating: 4.1,
    stock: 14,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 3499
  },
  {
    id: 18,
    name: "Smart Plug",
    image: "/images/plug.jpeg",
    description: "Wi-Fi enabled plug with timer and voice control",
    category: "Electronics",
    brand: "PlugSmart",
    rating: 4.5,
    stock: 30,
    warranty: "2 Years",
    delivery: "Free Delivery",
    price: 1799
  },
  {
    id: 19,
    name: "Cable Organizer",
    image: "/images/orgnizer.jpeg",
    description: "Magnetic clips for desk cable management",
    category: "Accessories",
    brand: "TidyTech",
    rating: 4.0,
    stock: 50,
    warranty: "6 Months",
    delivery: "Standard Delivery",
    price: 499
  },
  {
    id: 20,
    name: "Fingerprint Padlock",
    image: "/images/padlock.jpeg",
    description: "Biometric lock with USB charging",
    category: "Accessories",
    brand: "SecureLock",
    rating: 4.3,
    stock: 18,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 2999
  },
  {
    id: 22,
    name: "Sony WH-1000XM5",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=1000",
    description: "Industry-leading noise canceling with dual processor V1",
    category: "Electronics",
    brand: "Sony",
    rating: 4.9,
    stock: 12,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 85000
  },
  {
    id: 23,
    name: "Apple Watch Ultra 2",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=1000",
    description: "The most rugged and capable Apple Watch ever.",
    category: "Electronics",
    brand: "Apple",
    rating: 4.8,
    stock: 8,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 195000
  },
  {
    id: 24,
    name: "Logitech MX Master 3S",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=1000",
    description: "Ultrafast magspeed scrolling and 8K DPI tracking.",
    category: "Electronics",
    brand: "Logitech",
    rating: 4.7,
    stock: 25,
    warranty: "2 Years",
    delivery: "Free Delivery",
    price: 28500
  },
  {
    id: 25,
    name: "Keychron Q6 Mechanical",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=1000",
    description: "Full-size custom mechanical keyboard with QMK/VIA.",
    category: "Electronics",
    brand: "Keychron",
    rating: 4.9,
    stock: 5,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 45000
  },
  {
    id: 26,
    name: "DJI Mini 4 Pro",
    image: "/images/DJI Mini 4 Pro.jpeg",
    description: "Foldable mini-drone with 4K HDR video and omni sensing.",
    category: "Electronics",
    brand: "DJI",
    rating: 4.9,
    stock: 3,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 245000
  },
  {
    id: 27,
    name: "Samsung Odyssey G9",
    image: "/images/Samsung Odyssey G9.jpeg",
    description: "49 inch Dual QHD curved gaming monitor 240Hz.",
    category: "Electronics",
    brand: "Samsung",
    rating: 4.6,
    stock: 4,
    warranty: "3 Years",
    delivery: "Special Delivery",
    price: 320000
  },
  {
    id: 28,
    name: "Bose SoundLink Revolve",
    image: "https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&q=80&w=1000",
    description: "True 360-degree sound for consistent coverage.",
    category: "Electronics",
    brand: "Bose",
    rating: 4.5,
    stock: 15,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 54000
  },
  {
    id: 29,
    name: "GoPro HERO12 Black",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&q=80&w=1000",
    description: "Unbelievable image quality with 5.3K video resolution.",
    category: "Electronics",
    brand: "GoPro",
    rating: 4.7,
    stock: 10,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 125000
  },
  {
    id: 30,
    name: "Razer Nommo Pro",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=1000",
    description: "THX Certified premium 2.1 gaming speakers.",
    category: "Electronics",
    brand: "Razer",
    rating: 4.4,
    stock: 6,
    warranty: "2 Years",
    delivery: "Free Delivery",
    price: 145000
  },
  {
    id: 32,
    name: "Anker 737 Power Bank",
    image:"/images/Anker 737 Power Bank.jpeg",
    description: "Ultra-powerful 2-way charging 140W battery pack.",
    category: "Electronics",
    brand: "Anker",
    rating: 4.8,
    stock: 30,
    warranty: "18 Months",
    delivery: "Free Delivery",
    price: 38000
  },
  {
    id: 33,
    name: "Insta360 X4",
    image: "/images/Insta360 X4.jpeg",
    description: "8K 360 Degree action camera with AI editing features.",
    category: "Electronics",
    brand: "Insta360",
    rating: 4.9,
    stock: 7,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 155000
  },
  {
    id: 34,
    name: "ASUS ROG Swift OLED",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1000",
    description: "World's first 1440p OLED gaming monitor.",
    category: "Electronics",
    brand: "ASUS",
    rating: 4.8,
    stock: 2,
    warranty: "3 Years",
    delivery: "Special Delivery",
    price: 280000
  },
  {
    id: 35,
    name: "SteelSeries Arctis Nova Pro",
    image: "/images/SteelSeries Arctis Nova Pro.jpeg",
    description: "Multi-system gaming headset with active noise cancelling.",
    category: "Electronics",
    brand: "SteelSeries",
    rating: 4.6,
    stock: 9,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 98000
  },
  {
    id: 37,
    name: "Elgato Stream Deck MK.2",
    image: "/images/Elgato Stream Deck MK.2.jpeg",
    description: "15 customizable LCD keys to control apps and tools.",
    category: "Electronics",
    brand: "Elgato",
    rating: 4.9,
    stock: 14,
    warranty: "1 Year",
    delivery: "Free Delivery",
    price: 42000
  },
  {
    id: 38,
    name: "Belkin BoostCharge Pro",
    image: "/images/Belkin BoostCharge Pro.jpeg",
    description: "3-in-1 wireless charging pad with MagSafe for Apple.",
    category: "Electronics",
    brand: "Belkin",
    rating: 4.7,
    stock: 20,
    warranty: "2 Years",
    delivery: "Free Delivery",
    price: 32000
  },
];


// Sub categories ko aik mega array mein merge kiya
export const products = [...mobiles, ...laptops, ...electronics];
export default products;